import { useEffect } from "react";

const Privacy = () => {
    useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <section className="side-space section-space privacy-policy-section">
      <h1 className="mb-4">Privacy Policy</h1>
      <p>We, KitmeK Pvt Limited (“Kitmek”, “We”, “Company”) are the owners of the website https://www.kitmek.com (“Website”), and a mobile application Kitmec University (“the App”). The Users can through this AI-basedgaming platform play virtual games involving academics from kindergarten to Grade 5, interactive learning with AI teachers, quizzes and puzzles, where the User’s Child can learn languages, academic subjects and participate in several extra-curricular activities in a virtual manner under the supervision and guidance of the User referred to as the (“Services”).</p>
      <p>We respect data privacy rights and are committed to protecting personal information collected on this Website/App. This privacy policy (“Privacy Policy”) sets forth how we collect, use and protect the personal information collected on this Website/App.</p>
      <p>PLEASE READ THIS PRIVACY POLICY CAREFULLY. BY CONTINUING TO USE THE WEBSITE/APP, PROVIDING US PERSONAL INFORMATION, YOU CONSENT TO OUR USE OF YOUR PERSONAL INFORMATION IN ACCORDANCE WITH THE TERMS OF THIS PRIVACY POLICY. IF YOU DO NOT AGREE TO THIS PRIVACY POLICY, YOU MAY WITHDRAW YOUR CONSENT OR ALTERNATIVELY CHOOSE NOT TO PROVIDE YOUR PERSONAL INFORMATION ON THE WEBSITE/APP. SUCH AN INTIMATION TO WITHDRAW YOUR CONSENT CAN BE PROVIDED BY EMAIL TO COMMUNICATION DETAILS MENTIONED BELOW.</p>
      <p>IF YOU ARE ACCESSING THE WEBSITE/APP ON BEHALF OF A THIRD PARTY, YOU REPRESENT THAT YOU HAVE THE AUTHORITY TO BIND SUCH THIRD-PARTY TO THE TERMS AND CONDITIONS OF THIS PRIVACY POLICY AND, IN SUCH AN EVENT YOUR USE OF THE WEBSITE/APP SHALL REFER TO USE BY SUCH THIRD PARTY. IF YOU DO NOT HAVE SUCH AN AUTHORITY (TO PROVIDE ANY PERSONAL INFORMATION OF A THIRD PARTY) OR DO NOT AGREE TO THE TERMS OF THIS PRIVACY POLICY, THEN YOU SHOULD REFRAIN FROM USING THE WEBSITE/APP.</p>
      <p>This Privacy Policy is an electronic record in the form of an electronic contract being compliant and construed in accordance with The Indian Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 under The Information Technology Act 2000 (“Privacy Rules”) that require publishing of privacy policy for the collection, use, storage and transfer of sensitive personal data.</p>

      <ol className="list-number">
        <li>Definitions
          <ol className="list-[lower-roman]">
            <li><p><strong>“Sponsor”</strong> shall mean any person or any form of business entity who seeks to aid the Underprivileged Child under the Sponsorship Programme.</p></li>
            <li><p><strong>“Sponsorship Programme”</strong> shall mean a formal program where Underprivileged Child will be aided with free education by the sponsor.</p></li>
            <li><p><strong>“Underprivileged Child”</strong> shall mean any Child enrolling for the Sponsorship Programme through the User.</p></li>
            <li>
              <p><strong>“User(s)”, “you”, “your”</strong> shall mean individuals including but not limited to children, Underprivileged Child, and parents that avail the Services by creating a user account through the App.</p>
            </li>
            <li>
              <p><strong>“Visitor”</strong> shall mean individuals who visit the Website or may opt to share Personal Information to reach out to us.</p>
            </li>
          </ol>
        </li>
        <li>Personal Information Collected
            <p className="font-normal">For purposes of this Privacy Policy, <strong>“Personal Information”</strong> means information that can be used to personally identify the User, including but not limited to the User’s name, mobile number, email address. .</p>
                    <ol className="list-[lower-roman]">
            <li>
              <p><strong>Personal Information collected on the Website-</strong> To get in touch with us through the chatbox, contact us section on our Website, or to apply for a job with us, Visitors are required to provide their Personal Information.</p>
            </li>
            <li>
              <p><strong>Personal Information collected to provide the Services- </strong>To avail the Services, if the child is below the Age of 13 Years, we would need a parent to create an account for the child (“Parent Profile”). During the registration and validation process of such user account, and for availing the services, parent shall be required to enrol/share/upload certain Personal Information including but not limited to their name, child’s name, phone number, age, gender, country, grade details to give personalized experience to the User. Report card generated by the App will be shared with the Sponsors for participating in the Sponsorship Programme.</p>
            </li>
            <li>
              <p><strong>Social Media Platform –</strong> If you wish to subscribe to our blog, contact us through social media platforms such as LinkedIn, Facebook, Twitter etc. (“Social Media”), we may get access to your Personal Information on such Social Media (such as your name, email id, and phone).</p>
            </li>
            <li>
              <p><strong>Log Data – </strong>When you visit the Website or use the App directly or through third party websites, whether you have signed-in or are just browsing the Website, our servers automatically record information that your browser sends whenever you visit a website (“Log Data”). This Log Data may include information such as your computer’s Internet Protocol (“IP”) address, browser type or the webpage you were visiting before you came to our Website, pages of our Website and Subscription that you visit use, the time spent on those pages, information you search for on our Website, access times and dates, and other product performance and analytical data.</p>
            </li>
            <li>
              <p><strong>Payment Information-</strong> You may elect to pay for the Services through our Website/App, we may collect certain information such as name and email address to process your request. You will be required to provide certain payment information directly to our payment processing partners, including but not limited to your name, credit/debit card information. We do not access, store or collect your credit/debit card information.</p>
            </li>
          </ol>
        </li>
        <li>Cookies
          <p className="font-normal">We use cookies and/or similar in-house and third-party tracking tools to track user traffic patterns. Tracking tools also used are beacons, tags, and scripts to collect and track information and to improve and analyse our Website . You may choose to disable cookies through your browser settings.</p>
          <p className="font-normal">
            Types of Cookies used: We use the following types of Cookies
          </p>
          <ul className="list-disc font-normal">
            <li>Strictly necessary cookies</li>
            <li>Analytical/performance cookies.</li>
          </ul>
          <p className="font-normal ">
            We use cookies to:
          </p>
          <ul className="list-disc font-normal">
            <li>improve the User experience on the Website</li>
            <li>understand the usage based on the geographical area</li>
            <li>understand the usage based on the demographics</li>
            <li>understand and get usage patterns of the users</li>
          </ul>
          <p className="font-normal">The cookies will collect the following information:</p>
          <ul className="list-disc font-normal">
            <li>Clicks and scroll on the Website;</li>
            <li>User and Visitor’s operating system, browser information, CPU, GPU; and</li>
            <li>Information of service provider.</li>
          </ul>
          <p className="font-normal">Will disabling the cookies allow Users to use the Website?</p>
          <p className="font-normal">We will not restrict the usage of the Website if the cookies are disabled. Some features of the Website may be affected if the cookies are disabled.</p>
        </li>
        <li>Accuracy of information
          <p className="font-normal">User undertakes that he shall be solely responsible for the accuracy, correctness, or truthfulness of the Personal Information shared with us whether of its own or any third party. In the event the User is sharing any Personal Information on behalf of a third person, the User represents and warrants that he has the necessary authority to share such Personal Information with the Company, obtained a written consent from such third party and the Company shall not be responsible for verifying the same. The User understands and acknowledges that such Personal Information shall be subject to the terms and conditions of this Privacy Policy.</p>
        </li>
        <li>Use of Personal Information
          <p className="font-normal">We use the Personal Information for the following purposes:</p>
          <ol className="list-[lower-roman] font-normal">
            <li>to inform you about our Services and to respond to your requests;</li>
            <li>for creation or development of business intelligence or data analytics in relation to the Services provided by us</li>
            <li>to provide you with a better experience when you access our Website/App and to improve the Services;</li>
            <li>to maintain and manage our Website/App;</li>
            <li>to manage our relationship with you;</li>
            <li>for internal record keeping; and to comply with our legal or statutory obligations.</li>
          </ol>
        </li>
        <li>Disclosures
          <p className="font-normal">We do not sell, rent, share, distribute, lease or otherwise provide your Personal Information to third parties, without your prior consent. Keeping this in mind, we may disclose your Personal Information in the following cases:</p>
          <ol className="list-[lower-roman] font-normal">
            <li><strong>Affiliates:</strong> We may provide your Personal Information to our affiliates to enable them to improve the Offerings, provide feedback and respond to their queries.</li>
            <li><strong>Service Providers:</strong> We may share your Personal Information with the service providers who work with us in connection with operating the Website/App and/ or providing the Offerings. All such service providers are subject to stringent confidentiality restrictions consistent with this Privacy Policy.</li>
            <li><strong>Sponsors:</strong> In the event, you need any aid or would like to participate in Sponsorship Program then we may share your Personal Information with the Sponsors for the purpose of verification that may be conducted by the Sponsor for granting the aid/sponsorship.</li>
            <li><strong>Merger or Acquisition:</strong> We may transfer your Personal Information if we are acquired by another entity, or if we merge with another company or transfer a part of our business, including the Website/App, to a third party. Any such third party or resultant entity that receives your Personal Information shall have the right to continue to use your Personal Information in line with the purposes set out herein. In the event of such a sale or transfer, we may notify you.</li>
            <li><strong>Legal and Regulatory Authorities:</strong> We may disclose your Personal Information in order to comply with our legal obligations/ court orders/ requests by Govt. authorities.</li>
          </ol>
        </li>
        <li>Data Retention
          <p className="font-normal">We will retain User’s Personal Information as long as it is required to be retained for the purpose of provision of the Services. We may also retain and use User’s Personal Information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements. Security</p>
          <p className="font-normal">Your Personal Information is stored on third-party cloud infrastructure providers such as Microsoft Azure Server. Although we provide appropriate firewalls and protections, and have implemented encryption mechanisms, we cannot warrant the security of Personal Information transmitted as these systems are not hack proof. Data pilferage due to unauthorized hacking, virus attacks, technical issues is possible, and we will take necessary measures to mitigate such events.</p>
        </li>
        <li>Your Rights
          <p className="font-normal">You have the right to access Personal Information in our possession, right to have us rectify or modify any such Personal Information, right to have us erase/delete your Personal Information, right to restrict us from processing such Personal Information, right to object to our use of Personal Information, withdraw consent at any time where we are relying on consent to process Personal Information Depending on the nature of the request, we may ask you to complete a Personal Information request form or seek certain details to verify the request. All requests for Personal Information will be handled within a reasonable period of time. If you would like to exercise ANY of these rights, please contact contact@kitmek.com .</p>
        </li>
        <li>Choice and Opt-Out
          <p className="font-normal">We may send you communications including but not limited to (a) notices about your use of our Website/App and Services, including those concerning violations of use, (b) updates, (c) promotional information regarding our Services, and (d) newsletters. You may opt out of receiving promotional emails and newsletters from us by following the unsubscribe instructions provided in those emails. Alternatively, you can opt out, at any time, by emailing contact@kitmek.com with your specific request.</p>
        </li>
        <li>Children’s Privacy
          <p className="font-normal">
            We do not knowingly collect Personal Information from children under the age of thirteen (13) without verifiable parental consent. We do not use or disclose data collected from child users for targeted advertising or marketing purposes. We will not knowingly retain a child’s personal information after it is no longer needed for the purpose for which it was collected. If the legal representative of the child discovers that the child has provided us with Personal Information If it is determined that such information has been inadvertently collected on anyone under the age of thirteen (13), we request the legal representative of the child to contact us contact@kitmek.com to have the Personal Information deleted.
          </p>
        </li>
        <li>Links to other Websites
          <p className="font-normal">Our Website/App may contain links to other Platforms/applications of your interest. Please note that we do not have any control over such other Platforms/applications, and you will be accessing these Platforms/applications at your own risk. Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such Platforms/applications and those are not governed by this Privacy Policy. You should exercise caution and look at the privacy policy applicable to such Platforms/applications.</p>

        </li>
        <li>Limitation of liability
          <p className="font-normal">To the extent permissible under the law, we shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to, damages for loss of profits, goodwill, data, information, or other intangible losses (even if we have been advised of the possibility of such damages), arising out of this Privacy Policy.</p>
        </li>
        <li>Governing laws
          <p className="font-normal">This Privacy Policy shall in all respects be governed by and construed and enforced in accordance with the laws of India and the courts of Pune shall have exclusive jurisdiction to adjudicate any subject matter under this Privacy Policy.</p>
        </li>
        <li>Changes To This Policy
          <p className="font-normal">Please revisit this page periodically to stay aware of any changes to this Privacy Policy, which we may update from time to time. If we modify this Privacy Policy, we will make it available through the Website and indicate the date of the latest revision. If such modifications materially alter your rights or obligations hereunder, we will make reasonable efforts to notify you of the change via email or through our Website.</p>
          <p className="font-normal">This Privacy Policy was last modified on 9th January 2023</p>
        </li>
        <li>Contact us
          <p className="font-normal">If you have any questions or concerns or grievances regarding this Privacy Policy or wish to withdraw your consent in relation to the processing of your Personal Information you can reach out.</p>
        </li>
      </ol>
    </section>
  )
}

export default Privacy